idle_state:
    segments:
        - start: 0
          end: 70
          color1:
            r: 0
            g: 255
            b: 238
        - start: 44
          end: 150
          color1:
            r: 238
            g: 0
            b: 255
resubs:
    6becff14-aa60-4f38-8391-9309a6847bec:
        months: 4
        state:
            segments: []
        duration: 3s
    9da3b643-9a25-4230-a156-07eb9f7df8cb:
        months: 2
        state:
            fx: 134
            color1:
                r: 46
                g: 233
                b: 22
            color2:
                r: 255
                g: 234
                b: 0
            color3:
                r: 238
                g: 17
                b: 105
            segments: []
        duration: 3s
    67b1c1a1-948c-4c89-9057-bce88db01934:
        months: 3
        state:
            fx: 159
            color1:
                r: 251
                g: 255
                b: 0
            color2:
                r: 86
                g: 228
                b: 253
            color3:
                r: 136
                g: 18
                b: 121
            segments: []
        duration: 3s
    bfb72f2c-877e-495c-8a97-10adf60a4f0a:
        months: 1
        state:
            fx: 2
            color1:
                r: 17
                g: 255
                b: 0
            color2:
                r: 255
                g: 0
                b: 221
            color3:
                r: 114
                g: 175
                b: 241
            segments: []
        duration: 3s
patterns:
    7528ed6b-2ab8-47bb-a842-efb5f5832711:
        id: 7528ed6b-2ab8-47bb-a842-efb5f5832711
        name: 'Logo #1'
        segments:
            - start: 0
              end: 70
              color1:
                r: 0
                g: 255
                b: 238
            - start: 44
              end: 150
              color1:
                r: 238
                g: 0
                b: 255
