# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: internal/adapter/inbound/api/ui/app/package-lock.json
      - run: npm ci
        working-directory: internal/adapter/inbound/api/ui/app
      - run: npm run build
        working-directory: internal/adapter/inbound/api/ui/app
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
          cache-dependency-path: subdir/go.sum
      - name: Build
        run: GOOS=windows GOARCH=amd64 go build -v -ldflags -H=windowsgui -o companion.exe ./cmd

      - uses: actions/upload-artifact@v3
        with:
          name: companion
          path: companion.exe
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
